export const constants = {
  SEARCH_TEXT: "Dashboard/SEARCH_TEXT",
  TOGGLE_COMPLETE_PLATE: "Dashboard/TOGGLE_COMPLETE_PLATE",
  OPEN_CREATE_PLATE_DIALOG: "Dashboard/OPEN_CREATE_PLATE_DIALOG",
  CLOSE_CREATE_PLATE_DIALOG: "Dashboard/CLOSE_CREATE_PLATE_DIALOG",
  OPEN_REMOVE_PLATE_DIALOG: "Dashboard/OPEN_REMOVE_PLATE_DIALOG",
  CLOSE_REMOVE_PLATE_DIALOG: "Dashboard/CLOSE_REMOVE_PLATE_DIALOG"
};
